In [1]:
import pandas as pd
import numpy as np
import utm

In [ ]:
raw_data = pd.read_csv('/Users/cbc/Project/Python/DAMCourse/Assignment3/hwphase2data_update/test_2g.csv')

In [ ]:
gongcan = pd.read_csv('/Users/cbc/Project/Python/DAMCourse/Assignment3/hwphase2data_update/gongcan.csv')

In [ ]:
new_data = raw_data.values

In [ ]:
for mr in new_data:
    temp = gongcan[(gongcan['RNCID'] == mr[4]) & (gongcan['CellID'] == mr[5])]
    utm1, utm2, _, _ = utm.from_latlon(temp['Latitude'].values[0], temp['Longitude'].values[0])
    mr[4] = utm1
    mr[5] = utm2
    if -999 in mr[9:14]:
        mr[9:14] = mr[4:9]
    else:
        temp = gongcan[(gongcan['RNCID'] == mr[9]) & (gongcan['CellID'] == mr[10])]
        utm1, utm2, _, _ = utm.from_latlon(temp['Latitude'].values[0], temp['Longitude'].values[0])
        mr[9] = utm1
        mr[10] = utm2
    if -999 in mr[14:19]:
        mr[14:19] = mr[4:9]
    else:
        temp = gongcan[(gongcan['RNCID'] == mr[14]) & (gongcan['CellID'] == mr[15])]
        utm1, utm2, _, _ = utm.from_latlon(temp['Latitude'].values[0], temp['Longitude'].values[0])
        mr[14] = utm1
        mr[15] = utm2
    if -999 in mr[19:24]:
        mr[19:24] = mr[4:9]
    else:
        temp = gongcan[(gongcan['RNCID'] == mr[19]) & (gongcan['CellID'] == mr[20])]
        utm1, utm2, _, _ = utm.from_latlon(temp['Latitude'].values[0], temp['Longitude'].values[0])
        mr[19] = utm1
        mr[20] = utm2
    if -999 in mr[24:29]:
        mr[24:29] = mr[4:9]
    else:
        temp = gongcan[(gongcan['RNCID'] == mr[24]) & (gongcan['CellID'] == mr[25])]
        utm1, utm2, _, _ = utm.from_latlon(temp['Latitude'].values[0], temp['Longitude'].values[0])
        mr[24] = utm1
        mr[25] = utm2
    if -999 in mr[29:34]:
        mr[29:34] = mr[4:9]
    else:
        temp = gongcan[(gongcan['RNCID'] == mr[29]) & (gongcan['CellID'] == mr[30])]
        utm1, utm2, _, _ = utm.from_latlon(temp['Latitude'].values[0], temp['Longitude'].values[0])
        mr[29] = utm1
        mr[30] = utm2

In [ ]:
raw_data.head()

In [ ]:
new_df = pd.DataFrame(data=new_data, columns=raw_data.columns)

In [ ]:
new_df.head()

In [ ]:
new_df.to_csv('/Users/cbc/Project/Python/DAMCourse/Assignment3/hwphase2data_update/new_train.csv', index=False)

In [3]:
df = pd.read_csv('hwphase2data_update/new_train.csv')

In [4]:
df.head()

TrajID          IMEI          IMSI        MRTime        RNCID_1  \
0     0.0  8.613740e+14  4.600128e+14  1.507627e+09  329720.543832   
1     0.0  8.613740e+14  4.600128e+14  1.507627e+09  329980.001824   
2     0.0  8.613740e+14  4.600128e+14  1.507627e+09  329980.001824   
3     0.0  8.613740e+14  4.600128e+14  1.507627e+09  329980.001824   
4     0.0  8.613740e+14  4.600128e+14  1.507627e+09  329980.001824   

       CellID_1  Dbm_1  AsuLevel_1  SignalLevel_1        RNCID_2  ...  \
0  3.462947e+06  -79.0        17.0            4.0  329351.950099  ...   
1  3.463061e+06  -75.0        19.0            4.0  329351.950099  ...   
2  3.463061e+06  -75.0        19.0            4.0  329351.950099  ...   
3  3.463061e+06  -73.0        20.0            4.0  329351.950099  ...   
4  3.463061e+06  -73.0        20.0            4.0  329351.950099  ...   

         RNCID_6      CellID_6  Dbm_6  AsuLevel_6  SignalLevel_6   Longitude  \
0  330416.573534  3.463404e+06  -87.0        13.0            4.0  121.213610   
1  330416.573534  3.463404e+06  -87.0        13.0            4.0  121.213575   
2  330416.573534  3.463404e+06  -87.0        13.0            4.0  121.213583   
3  330416.573534  3.463404e+06  -85.0        14.0            4.0  121.213605   
4  330416.573534  3.463404e+06  -83.0        15.0            4.0  121.213596   

    Latitude  Altitude  Accuracy  Speed  
0  31.289266      23.0       3.0   0.68  
1  31.289228      -7.0       8.0   0.00  
2  31.289263       1.0       5.0   0.00  
3  31.289285      -5.0       7.0   0.00  
4  31.289288      -1.0       4.0   0.00  

[5 rows x 39 columns]

In [5]:
from sklearn.preprocessing import minmax_scale

In [6]:
data = df.values

In [7]:
len(data)

10047

In [8]:
scaler = minmax_scale(np.concatenate([data[:,4],data[:,9],data[:,14],data[:,19],data[:,24],data[:,29]]))
scaler

array([0.2090824 , 0.22193051, 0.22193051, ..., 0.19087762, 0.19087762,
       0.23222723])

In [9]:
df['RNCID_1'] = scaler[0:10047]

In [10]:
scaler[0:10047]

array([0.2090824 , 0.22193051, 0.22193051, ..., 0.19087762, 0.19087762,
       0.23222723])

In [11]:
df['RNCID_2'] = scaler[10047:10047*2]

In [12]:
df['RNCID_3'] = scaler[10047*2:10047*3]

In [13]:
df['RNCID_4'] = scaler[10047*3:10047*4]

In [14]:
df['RNCID_5'] = scaler[10047*4:10047*5]

In [15]:
df['RNCID_6'] = scaler[10047*5:10047*6]

In [16]:
scaler = minmax_scale(np.concatenate([data[:,5],data[:,10],data[:,15],data[:,20],data[:,25],data[:,30]]))
scaler

array([0.60634322, 0.61902311, 0.61902311, ..., 0.5551795 , 0.5551795 ,
       0.66154756])

In [17]:
df['CellID_1'] = scaler[0:10047]

In [18]:
df['CellID_2'] = scaler[10047:10047*2]

In [19]:
df['CellID_3'] = scaler[10047*2:10047*3]

In [20]:
df['CellID_4'] = scaler[10047*3:10047*4]

In [21]:
df['CellID_5'] = scaler[10047*4:10047*5]

In [22]:
df['CellID_6'] = scaler[10047*5:10047*6]

In [23]:
scaler = minmax_scale(np.concatenate([data[:,6],data[:,11],data[:,16],data[:,21],data[:,26],data[:,31]]))
scaler

array([0.5483871 , 0.61290323, 0.61290323, ..., 0.83870968, 0.77419355,
       0.87096774])

In [24]:
df['Dbm_1'] = scaler[0:10047]

In [25]:
df['Dbm_2'] = scaler[10047:10047*2]

In [26]:
df['Dbm_3'] = scaler[10047*2:10047*3]

In [27]:
df['Dbm_4'] = scaler[10047*3:10047*4]

In [28]:
df['Dbm_5'] = scaler[10047*4:10047*5]

In [29]:
df['Dbm_6'] = scaler[10047*5:10047*6]

In [30]:
scaler = minmax_scale(np.concatenate([data[:,7],data[:,12],data[:,17],data[:,22],data[:,27],data[:,32]]))
scaler

array([0.5483871 , 0.61290323, 0.61290323, ..., 0.83870968, 0.77419355,
       0.87096774])

In [31]:
df['AsuLevel_1'] = scaler[0:10047]
df['AsuLevel_2'] = scaler[10047:10047*2]
df['AsuLevel_3'] = scaler[10047*2:10047*3]
df['AsuLevel_4'] = scaler[10047*3:10047*4]
df['AsuLevel_5'] = scaler[10047*4:10047*5]
df['AsuLevel_6'] = scaler[10047*5:10047*6]

In [32]:
scaler = minmax_scale(np.concatenate([data[:,8],data[:,13],data[:,18],data[:,23],data[:,28],data[:,33]]))
scaler

array([1., 1., 1., ..., 1., 1., 1.])

In [33]:
df['SignalLevel_1'] = scaler[0:10047]
df['SignalLevel_2'] = scaler[10047:10047*2]
df['SignalLevel_3'] = scaler[10047*2:10047*3]
df['SignalLevel_4'] = scaler[10047*3:10047*4]
df['SignalLevel_5'] = scaler[10047*4:10047*5]
df['SignalLevel_6'] = scaler[10047*5:10047*6]

In [34]:
df.head()

TrajID          IMEI          IMSI        MRTime   RNCID_1  CellID_1  \
0     0.0  8.613740e+14  4.600128e+14  1.507627e+09  0.209082  0.606343   
1     0.0  8.613740e+14  4.600128e+14  1.507627e+09  0.221931  0.619023   
2     0.0  8.613740e+14  4.600128e+14  1.507627e+09  0.221931  0.619023   
3     0.0  8.613740e+14  4.600128e+14  1.507627e+09  0.221931  0.619023   
4     0.0  8.613740e+14  4.600128e+14  1.507627e+09  0.221931  0.619023   

      Dbm_1  AsuLevel_1  SignalLevel_1  RNCID_2  ...   RNCID_6  CellID_6  \
0  0.548387    0.548387            1.0  0.19083  ...  0.243549  0.657076   
1  0.612903    0.612903            1.0  0.19083  ...  0.243549  0.657076   
2  0.612903    0.612903            1.0  0.19083  ...  0.243549  0.657076   
3  0.645161    0.645161            1.0  0.19083  ...  0.243549  0.657076   
4  0.645161    0.645161            1.0  0.19083  ...  0.243549  0.657076   

      Dbm_6  AsuLevel_6  SignalLevel_6   Longitude   Latitude  Altitude  \
0  0.419355    0.419355            1.0  121.213610  31.289266      23.0   
1  0.419355    0.419355            1.0  121.213575  31.289228      -7.0   
2  0.419355    0.419355            1.0  121.213583  31.289263       1.0   
3  0.451613    0.451613            1.0  121.213605  31.289285      -5.0   
4  0.483871    0.483871            1.0  121.213596  31.289288      -1.0   

   Accuracy  Speed  
0       3.0   0.68  
1       8.0   0.00  
2       5.0   0.00  
3       7.0   0.00  
4       4.0   0.00  

[5 rows x 39 columns]

In [35]:
df.to_csv('/Users/cbc/Project/Python/DAMCourse/Assignment3/hwphase2data_update/new_formatted_data2.csv', index=False)